#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Мягкий патч Flutter-android модуля (Groovy/KTS):
- включает coreLibraryDesugaring в android/app
- добавляет зависимость desugar_jdk_libs (2.0.4)
- выставляет Java 17 и kotlin jvmTarget=17
- НЕ трогает версии AGP/Kotlin/Gradle и settings.gradle*

Запуск:
  python3 tools/patch_gradle.py app
  python3 tools/patch_gradle.py app/android   # тоже ок
"""

import sys
import pathlib
import re

DESUGAR_VER = "2.0.4"

def read(p: pathlib.Path) -> str:
    return p.read_text(encoding="utf-8", errors="ignore")

def write(p: pathlib.Path, s: str):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")

def norm_app(arg: str) -> pathlib.Path:
    base = pathlib.Path(arg).resolve()
    return base.parent if base.name == "android" else base

def patch_app_groovy(f: pathlib.Path):
    if not f.exists():
        # Минимальный файл, если вдруг пусто
        write(f, f"""// Generated by patch_gradle.py (gentle)
plugins {{
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}}

android {{
    compileSdk 34

    defaultConfig {{
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }}

    buildTypes {{
        release {{
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }}
    }}

    compileOptions {{
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }}
    kotlinOptions {{
        jvmTarget = "17"
    }}
}}

dependencies {{
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:{DESUGAR_VER}"
}}
""")
        return

    txt = read(f)

    # 1) compileOptions + desugaring
    if "compileOptions" in txt:
        txt = re.sub(
            r"compileOptions\s*\{[\s\S]*?\}",
            """compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }""",
            txt, count=1
        )
    else:
        txt = re.sub(
            r"android\s*\{",
            """android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }""",
            txt, count=1
        )

    # 2) kotlinOptions jvmTarget=17
    if "kotlinOptions" in txt:
        txt = re.sub(
            r'kotlinOptions\s*\{[\s\S]*?\}',
            'kotlinOptions {\n        jvmTarget = "17"\n    }',
            txt, count=1
        )
    else:
        txt = re.sub(
            r"android\s*\{",
            """android {
    kotlinOptions {
        jvmTarget = "17"
    }""",
            txt, count=1
        )

    # 3) dependency на desugar_jdk_libs
    if "coreLibraryDesugaring" not in txt:
        if re.search(r"dependencies\s*\{", txt):
            txt = re.sub(
                r"dependencies\s*\{",
                f"""dependencies {{
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:{DESUGAR_VER}" """,
                txt, count=1
            )
        else:
            txt += f"""

dependencies {{
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:{DESUGAR_VER}"
}}
"""

    write(f, txt)

def patch_app_kts(f: pathlib.Path):
    if not f.exists():
        write(f, f"""// Generated by patch_gradle.py (gentle, KTS)
plugins {{
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}}

android {{
    compileSdk = 34

    defaultConfig {{
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }}

    buildTypes {{
        release {{
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }}
    }}

    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }}
    kotlinOptions {{
        jvmTarget = "17"
    }}
}}

dependencies {{
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:{DESUGAR_VER}")
}}
""")
        return

    txt = read(f)

    # 1) compileOptions
    if "compileOptions" in txt:
        txt = re.sub(
            r"compileOptions\s*\{[\s\S]*?\}",
            """compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }""",
            txt, count=1
        )
    else:
        txt = re.sub(
            r"android\s*\{",
            """android {
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }""",
            txt, count=1
        )

    # 2) kotlinOptions
    if "kotlinOptions" in txt:
        txt = re.sub(
            r'kotlinOptions\s*\{[\s\S]*?\}',
            'kotlinOptions {\n        jvmTarget = "17"\n    }',
            txt, count=1
        )
    else:
        txt = re.sub(
            r"android\s*\{",
            """android {
    kotlinOptions {
        jvmTarget = "17"
    }""",
            txt, count=1
        )

    # 3) dependency
    if "coreLibraryDesugaring(" not in txt:
        if re.search(r"dependencies\s*\{", txt):
            txt = re.sub(
                r"dependencies\s*\{",
                f"""dependencies {{
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:{DESUGAR_VER}") """,
                txt, count=1
            )
        else:
            txt += f"""

dependencies {{
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:{DESUGAR_VER}")
}}
"""
    write(f, txt)

def main():
    if len(sys.argv) < 1:
        print("Usage: python3 tools/patch_gradle.py app_or_app_android", file=sys.stderr)
        sys.exit(1)

    target = sys.argv[1] if len(sys.argv) >= 2 else "app"
    app_dir = norm_app(target)

    app_groovy = app_dir / "android" / "app" / "build.gradle"
    app_kts    = app_dir / "android" / "app" / "build.gradle.kts"

    if app_kts.exists() and not app_groovy.exists():
        patch_app_kts(app_kts)
    elif app_groovy.exists():
        patch_app_groovy(app_groovy)
    else:
        # Если нет ничего — создадим KTS как современный вариант
        patch_app_kts(app_kts)

    print("✅ Gentle patch applied: desugaring + Java 17 set in android/app (Groovy/KTS).")

if __name__ == "__main__":
    main()
