#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Единый патч для Flutter-обёртки (android/app):
- Java 17 + desugaring (desugar_jdk_libs:2.0.4)
- multidex (androidx.multidex:multidex:2.0.1) + multiDexEnabled
- packaging (гасим META-INF конфликты)
- lint (abortOnError=false, checkReleaseBuilds=false)
- android:exported="true" у лаунчер-activity
- namespace/applicationId = com.example.bp_logger
Работает и для Groovy (build.gradle), и для Kotlin DSL (build.gradle.kts).
"""

import sys, pathlib, re

DESUGAR = "com.android.tools:desugar_jdk_libs:2.0.4"
MULTIDEX = "androidx.multidex:multidex:2.0.1"
NAMESPACE = "com.example.bp_logger"

def read(p: pathlib.Path) -> str:
    return p.read_text(encoding="utf-8", errors="ignore")

def write(p: pathlib.Path, s: str):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")

def patch_manifest(app_root: pathlib.Path):
    mf = app_root / "android/app/src/main/AndroidManifest.xml"
    if not mf.exists():
        write(mf, f"""<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{NAMESPACE}">
  <application
      android:label="bp_logger"
      android:name="${{applicationName}}"
      android:icon="@mipmap/ic_launcher">
    <activity
        android:name=".MainActivity"
        android:exported="true"
        android:launchMode="singleTop"
        android:theme="@style/LaunchTheme"
        android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
        android:hardwareAccelerated="true"
        android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <meta-data android:name="flutterEmbedding" android:value="2" />
  </application>
</manifest>
""")
        return
    txt = read(mf)
    if "android:exported" not in txt:
        txt = re.sub(r'(<activity\b[^>]*>)',
                     lambda m: m.group(1).replace(">", ' android:exported="true">', 1),
                     txt, count=1)
    if 'android:name="flutterEmbedding"' not in txt:
        txt = txt.replace("</application>",
                          '    <meta-data android:name="flutterEmbedding" android:value="2" />\n  </application>')
    write(mf, txt)

def groovy(f: pathlib.Path) -> bool: return f.suffix == ".gradle"
def kts(f: pathlib.Path) -> bool: return f.suffix == ".kts"

def patch_app_gradle_groovy(f: pathlib.Path):
    if not f.exists():
        write(f, f"""// Generated by patch_android.py (Groovy)
plugins {{
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}}
android {{
    namespace "{NAMESPACE}"
    compileSdk 34
    defaultConfig {{
        applicationId "{NAMESPACE}"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }}
    buildTypes {{
        release {{
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }}
    }}
    compileOptions {{
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }}
    kotlinOptions {{
        jvmTarget = "17"
    }}
    lintOptions {{
        abortOnError false
        checkReleaseBuilds false
    }}
    packagingOptions {{
        resources {{
            excludes += ["META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES"]
        }}
    }}
}}
dependencies {{
    coreLibraryDesugaring "{DESUGAR}"
    implementation "{MULTIDEX}"
}}
""")
        return

    txt = read(f)
    if "namespace" not in txt:
        txt = re.sub(r"android\s*\{", f'android {{\n    namespace "{NAMESPACE}"', txt, count=1)
    if "applicationId" not in txt:
        txt = re.sub(r"defaultConfig\s*\{", f'defaultConfig {{\n        applicationId "{NAMESPACE}"', txt, count=1)

    if "compileOptions" in txt:
        txt = re.sub(r"compileOptions\s*\{[\s\S]*?\}",
                     """compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }""", txt, count=1)

    if "kotlinOptions" in txt:
        txt = re.sub(r'kotlinOptions\s*\{[\s\S]*?\}', 'kotlinOptions {\n        jvmTarget = "17"\n    }', txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    kotlinOptions {
        jvmTarget = "17"
    }""", txt, count=1)

    if re.search(r"defaultConfig\s*\{", txt) and not re.search(r"multiDexEnabled\s+true", txt):
        txt = re.sub(r"(defaultConfig\s*\{[^\}]*?)\}", r"\1\n        multiDexEnabled true\n    }", txt, count=1)

    if "lintOptions" in txt:
        txt = re.sub(r"lintOptions\s*\{[\s\S]*?\}",
                     """lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }""", txt, count=1)

    if "packagingOptions" in txt:
        txt = re.sub(r"packagingOptions\s*\{[\s\S]*?\}",
                     """packagingOptions {
        resources {
            excludes += ["META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES"]
        }
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    packagingOptions {
        resources {
            excludes += ["META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES"]
        }
    }""", txt, count=1)

    if "dependencies" in txt:
        if "coreLibraryDesugaring" not in txt:
            txt = re.sub(r"dependencies\s*\{",
                         f"""dependencies {{
    coreLibraryDesugaring "{DESUGAR}" """, txt, count=1)
        if "androidx.multidex:multidex" not in txt:
            txt = re.sub(r"dependencies\s*\{",
                         f"""dependencies {{
    implementation "{MULTIDEX}" """, txt, count=1)
    else:
        txt += f"""

dependencies {{
    coreLibraryDesugaring "{DESUGAR}"
    implementation "{MULTIDEX}"
}}
"""
    write(f, txt)

def patch_app_gradle_kts(f: pathlib.Path):
    if not f.exists():
        write(f, f"""// Generated by patch_android.py (KTS)
plugins {{
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}}
android {{
    namespace = "{NAMESPACE}"
    compileSdk = 34
    defaultConfig {{
        applicationId = "{NAMESPACE}"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        multiDexEnabled = true
    }}
    buildTypes {{
        release {{
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }}
    }}
    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }}
    kotlinOptions {{
        jvmTarget = "17"
    }}
    lint {{
        abortOnError = false
        checkReleaseBuilds = false
    }}
    packaging {{
        resources {{
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }}
    }}
}}
dependencies {{
    coreLibraryDesugaring("{DESUGAR}")
    implementation("{MULTIDEX}")
}}
""")
        return

    txt = read(f)

    if not re.search(r"\bnamespace\s*=", txt):
        txt = re.sub(r"android\s*\{", f'android {{\n    namespace = "{NAMESPACE}"', txt, count=1)
    if not re.search(r"\bapplicationId\s*=", txt):
        txt = re.sub(r"defaultConfig\s*\{", f'defaultConfig {{\n        applicationId = "{NAMESPACE}"', txt, count=1)

    if "compileOptions" in txt:
        txt = re.sub(r"compileOptions\s*\{[\s\S]*?\}",
                     """compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }""", txt, count=1)

    if "kotlinOptions" in txt:
        txt = re.sub(r'kotlinOptions\s*\{[\s\S]*?\}', 'kotlinOptions {\n        jvmTarget = "17"\n    }', txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    kotlinOptions {
        jvmTarget = "17"
    }""", txt, count=1)

    if re.search(r"defaultConfig\s*\{", txt) and not re.search(r"multiDexEnabled\s*=\s*true", txt):
        txt = re.sub(r"(defaultConfig\s*\{[^\}]*?)\}", r"\1\n        multiDexEnabled = true\n    }", txt, count=1)

    if re.search(r"\blint\s*\{", txt):
        txt = re.sub(r"lint\s*\{[\s\S]*?\}",
                     """lint {
        abortOnError = false
        checkReleaseBuilds = false
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    lint {
        abortOnError = false
        checkReleaseBuilds = false
    }""", txt, count=1)

    if re.search(r"\bpackaging\s*\{", txt):
        txt = re.sub(r"packaging\s*\{[\s\S]*?\}",
                     """packaging {
        resources {
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    packaging {
        resources {
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }
    }""", txt, count=1)

    if "coreLibraryDesugaring(" not in txt:
        txt = re.sub(r"dependencies\s*\{",
                     f"""dependencies {{
    coreLibraryDesugaring("{DESUGAR}") """, txt, count=1)
    if "androidx.multidex:multidex" not in txt:
        txt = re.sub(r"dependencies\s*\{",
                     f"""dependencies {{
    implementation("{MULTIDEX}") """, txt, count=1)

    write(f, txt)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 tools/patch_android.py app_dir", file=sys.stderr)
        sys.exit(1)

    app = pathlib.Path(sys.argv[1]).resolve()

    # Manifest
    patch_manifest(app)

    # Gradle (Groovy/KTS)
    g = app / "android/app/build.gradle"
    k = app / "android/app/build.gradle.kts"
    if k.exists() and not g.exists():
        patch_app_gradle_kts(k)
    elif g.exists():
        patch_app_gradle_groovy(g)
    else:
        patch_app_gradle_kts(k)

    print("✅ Patched: Manifest + Gradle (Java17, desugaring, multidex, packaging, lint, exported, namespace/appId).")

if __name__ == "__main__":
    main()
