#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Единый патч для Flutter Android wrapper
Поддержка Groovy и Kotlin DSL
Java 17 + desugaring + multidex + exported + namespace
"""

import sys
import pathlib
import re

DESUGAR = "com.android.tools:desugar_jdk_libs:2.0.4"
MULTIDEX = "androidx.multidex:multidex:2.0.1"
NAMESPACE = "com.example.bp_logger"
APPLICATION_ID = NAMESPACE

def read(p: pathlib.Path) -> str:
    return p.read_text(encoding="utf-8", errors="ignore")

def write(p: pathlib.Path, s: str):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")

def patch_manifest(app_root: pathlib.Path):
    mf = app_root / "android/app/src/main/AndroidManifest.xml"
    default_manifest = f'''<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{NAMESPACE}">

    <application
        android:label="bp_logger"
        android:name="${{applicationName}}"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>'''

    if not mf.exists():
        write(mf, default_manifest)
        return

    txt = read(mf)

    # Добавляем android:exported="true" только к MainActivity
    if 'android:exported=' not in txt:
        txt = re.sub(
            r'(<activity\s+android:name="\.MainActivity"[^>]*)',
            r'\1 android:exported="true"',
            txt,
            count=1
        )

    # Добавляем flutterEmbedding meta-data
    if 'flutterEmbedding' not in txt:
        txt = txt.replace(
            '</application>',
            '    <meta-data android:name="flutterEmbedding" android:value="2" />\n  </application>'
        )

    write(mf, txt)

def patch_gradle_groovy(file: pathlib.Path):
    if not file.exists():
        content = f'''// Auto-generated by patch_android.py
plugins {{
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}}

android {{
    namespace "{NAMESPACE}"
    compileSdk 34

    defaultConfig {{
        applicationId "{APPLICATION_ID}"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }}

    buildTypes {{
        release {{
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }}
    }}

    compileOptions {{
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }}

    kotlinOptions {{
        jvmTarget = "17"
    }}

    lintOptions {{
        abortOnError false
        checkReleaseBuilds false
    }}

    packagingOptions {{
        resources {{
            excludes += ["META-INF/AL2.0", "META-INF/LGPL2.1", "META-INF/LICENSE*", "META-INF/NOTICE*", "META-INF/DEPENDENCIES"]
        }}
    }}
}}

dependencies {{
    coreLibraryDesugaring "{DESUGAR}"
    implementation "{MULTIDEX}"
}}
'''
        write(file, content)
        return

    txt = read(file)

    # namespace & applicationId
    if "namespace" not in txt:
        txt = re.sub(r"(android\s*\{)", f"\\1\n    namespace \"{NAMESPACE}\"", txt, count=1)
    if "applicationId" not in txt:
        txt = re.sub(r"(defaultConfig\s*\{)", f"\\1\n        applicationId \"{APPLICATION_ID}\"", txt, count=1)

    # compileOptions
    txt = re.sub(
        r"compileOptions\s*\{[\s\S]*?\}",
        """compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }""",
        txt, count=1, flags=re.IGNORECASE
    ) or re.sub(
        r"(android\s*\{)", "\\1\n    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n        coreLibraryDesugaringEnabled true\n    }", txt, count=1
    )

    # kotlinOptions
    txt = re.sub(
        r"kotlinOptions\s*\{[\s\S]*?\}",
        "kotlinOptions {\n        jvmTarget = \"17\"\n    }",
        txt, count=1
    ) or re.sub(
        r"(android\s*\{)", "\\1\n    kotlinOptions {\n        jvmTarget = \"17\"\n    }", txt, count=1
    )

    # multiDexEnabled
    if "multiDexEnabled" not in txt:
        txt = re.sub(
            r"(defaultConfig\s*\{[^}]*?)(\s*\})",
            "\\1\n        multiDexEnabled true\\2",
            txt, count=1
        )

    # lintOptions
    txt = re.sub(
        r"lintOptions\s*\{[\s\S]*?\}",
        """lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }""",
        txt, count=1
    ) or re.sub(
        r"(android\s*\{)", "\\1\n    lintOptions {\n        abortOnError false\n        checkReleaseBuilds false\n    }", txt, count=1
    )

    # packagingOptions
    packaging_block = '''packagingOptions {
        resources {
            excludes += ["META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES"]
        }
    }'''
    if "packagingOptions" not in txt:
        txt = re.sub(r"(android\s*\{)", f"\\1\n    {packaging_block}", txt, count=1)

    # dependencies
    if "dependencies" not in txt:
        txt += f"\n\ndependencies {{\n    coreLibraryDesugaring \"{DESUGAR}\"\n    implementation \"{MULTIDEX}\"\n}}\n"
    else:
        if "coreLibraryDesugaring" not in txt:
            txt = re.sub(r"(dependencies\s*\{)", f"\\1\n    coreLibraryDesugaring \"{DESUGAR}\"", txt)
        if "androidx.multidex:multidex" not in txt:
            txt = re.sub(r"(dependencies\s*\{)", f"\\1\n    implementation \"{MULTIDEX}\"", txt)

    write(file, txt)

def patch_gradle_kts(file: pathlib.Path):
    if not file.exists():
        content = f'''// Auto-generated by patch_android.py (KTS)
plugins {{
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}}

android {{
    namespace = "{NAMESPACE}"
    compileSdk = 34

    defaultConfig {{
        applicationId = "{APPLICATION_ID}"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        multiDexEnabled = true
    }}

    buildTypes {{
        release {{
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }}
    }}

    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }}

    kotlinOptions {{
        jvmTarget = "17"
    }}

    lint {{
        abortOnError = false
        checkReleaseBuilds = false
    }}

    packaging {{
        resources {{
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }}
    }}
}}

dependencies {{
    coreLibraryDesugaring("{DESUGAR}")
    implementation("{MULTIDEX}")
}}
'''
        write(file, content)
        return

    txt = read(file)

    # namespace & applicationId
    if 'namespace =' not in txt:
        txt = re.sub(r"(android\s*\{)", f'\\1\n    namespace = "{NAMESPACE}"', txt, count=1)
    if 'applicationId =' not in txt:
        txt = re.sub(r"(defaultConfig\s*\{)", f'\\1\n        applicationId = "{APPLICATION_ID}"', txt, count=1)

    # compileOptions
    txt = re.sub(
        r"compileOptions\s*\{[\s\S]*?\}",
        """compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }""",
        txt, count=1
    ) or re.sub(
        r"(android\s*\{)", "\\1\n    compileOptions {\n        sourceCompatibility = JavaVersion.VERSION_17\n        targetCompatibility = JavaVersion.VERSION_17\n        isCoreLibraryDesugaringEnabled = true\n    }", txt, count=1
    )

    # kotlinOptions
    txt = re.sub(
        r"kotlinOptions\s*\{[\s\S]*?\}",
        'kotlinOptions {\n        jvmTarget = "17"\n    }',
        txt, count=1
    ) or re.sub(
        r"(android\s*\{)", "\\1\n    kotlinOptions {\n        jvmTarget = \"17\"\n    }", txt, count=1
    )

    # multiDexEnabled
    if "multiDexEnabled" not in txt:
        txt = re.sub(
            r"(defaultConfig\s*\{[^}]*?)(\s*\})",
            "\\1\n        multiDexEnabled = true\\2",
            txt, count=1
        )

    # lint
    txt = re.sub(
        r"lint\s*\{[\s\S]*?\}",
        """lint {
        abortOnError = false
        checkReleaseBuilds = false
    }""",
        txt, count=1
    ) or re.sub(
        r"(android\s*\{)", "\\1\n    lint {\n        abortOnError = false\n        checkReleaseBuilds = false\n    }", txt, count=1
    )

    # packaging
    packaging_block = '''packaging {
        resources {
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }
    }'''
    if "packaging" not in txt:
        txt = re.sub(r"(android\s*\{)", f"\\1\n    {packaging_block}", txt, count=1)

    # dependencies
    if "dependencies" not in txt:
        txt += f'\n\ndependencies {{\n    coreLibraryDesugaring("{DESUGAR}")\n    implementation("{MULTIDEX}")\n}}\n'
    else:
        if 'coreLibraryDesugaring' not in txt:
            txt = re.sub(r"(dependencies\s*\{)", f'\\1\n    coreLibraryDesugaring("{DESUGAR}")', txt)
        if 'implementation.*multidex' not in txt:
            txt = re.sub(r"(dependencies\s*\{)", f'\\1\n    implementation("{MULTIDEX}")', txt)

    write(file, txt)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 tools/patch_android.py <path_to_app_directory>", file=sys.stderr)
        sys.exit(1)

    app_root = pathlib.Path(sys.argv[1]).resolve()
    if not (app_root / "pubspec.yaml").exists():
        print(f"Error: {app_root} не похоже на Flutter-проект (нет pubspec.yaml)", file=sys.stderr)
        sys.exit(1)

    patch_manifest(app_root)

    groovy_file = app_root / "android/app/build.gradle"
    kts_file = app_root / "android/app/build.gradle.kts"

    if kts_file.exists():
        patch_gradle_kts(kts_file)
    elif groovy_file.exists():
        patch_gradle_groovy(groovy_file)
    else:
        # создаём KTS по умолчанию
        patch_gradle_kts(kts_file)

    print("Patched Android: Java17 + desugaring + multidex + exported + namespace")

if __name__ == "__main__":
    main()
