#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Мягкий, но «железный» патч модуля android/app (Groovy или Kotlin DSL):
- Java 17 + desugaring (desugar_jdk_libs 2.0.4)
- Включаем MultiDex (64K+) и зависимость androidx.multidex:2.0.1
- Отключаем фатальные Lint-ошибки для release (abortOnError=false)
- Добавляем packagingOptions (гасим частые конфликты META-INF*)
- Ничего не трогаем в settings.gradle* и версиях AGP/Kotlin/Gradle

Запуск:
  python3 tools/patch_gradle.py app
  python3 tools/patch_gradle.py app/android
"""

import sys
import pathlib
import re

DESUGAR_VER = "2.0.4"
MULTIDEX_VER = "2.0.1"

def read(p: pathlib.Path) -> str:
    return p.read_text(encoding="utf-8", errors="ignore")

def write(p: pathlib.Path, s: str):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")

def norm_app(arg: str) -> pathlib.Path:
    base = pathlib.Path(arg).resolve()
    return base.parent if base.name == "android" else base

# ---------------- Groovy ----------------
def patch_app_groovy(f: pathlib.Path):
    if not f.exists():
        # Создаём минимальный app/build.gradle, если его нет
        write(f, f"""// Generated by patch_gradle.py
plugins {{
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}}

android {{
    compileSdk 34

    defaultConfig {{
        applicationId "com.example.bp_logger"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }}

    buildTypes {{
        release {{
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }}
    }}

    compileOptions {{
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }}
    kotlinOptions {{
        jvmTarget = "17"
    }}

    lintOptions {{
        abortOnError false
        checkReleaseBuilds false
    }}

    packagingOptions {{
        resources {{
            excludes += ["META-INF/AL2.0", "META-INF/LGPL2.1", "META-INF/LICENSE*", "META-INF/NOTICE*", "META-INF/DEPENDENCIES"]
        }}
    }}
}}

dependencies {{
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:{DESUGAR_VER}"
    implementation "androidx.multidex:multidex:{MULTIDEX_VER}"
}}
""")
        return

    txt = read(f)

    # compileOptions + desugaring
    if "compileOptions" in txt:
        txt = re.sub(
            r"compileOptions\s*\{[\s\S]*?\}",
            """compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }""",
            txt, count=1
        )
    else:
        txt = re.sub(r"android\s*\{", """android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }""", txt, count=1)

    # kotlinOptions jvmTarget=17
    if "kotlinOptions" in txt:
        txt = re.sub(r'kotlinOptions\s*\{[\s\S]*?\}',
                     'kotlinOptions {\n        jvmTarget = "17"\n    }', txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    kotlinOptions {
        jvmTarget = "17"
    }""", txt, count=1)

    # defaultConfig { multiDexEnabled true }
    if re.search(r"defaultConfig\s*\{", txt):
        if not re.search(r"multiDexEnabled\s+true", txt):
            txt = re.sub(r"(defaultConfig\s*\{[^\}]*?)\}",
                         r"\1\n        multiDexEnabled true\n    }",
                         txt, count=1)
    else:
        txt = re.sub(r"android\s*\{",
                     """android {
    defaultConfig {
        multiDexEnabled true
    }""", txt, count=1)

    # lintOptions { abortOnError false; checkReleaseBuilds false }
    if "lintOptions" in txt:
        txt = re.sub(r"lintOptions\s*\{[\s\S]*?\}",
                     """lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }""", txt, count=1)

    # packagingOptions resources excludes
    if "packagingOptions" in txt:
        # нормализуем блок на случай отсутствия excludes
        if "resources" in txt:
            txt = re.sub(r"packagingOptions\s*\{[\s\S]*?\}",
                         """packagingOptions {
        resources {
            excludes += ["META-INF/AL2.0", "META-INF/LGPL2.1", "META-INF/LICENSE*", "META-INF/NOTICE*", "META-INF/DEPENDENCIES"]
        }
    }""", txt, count=1)
        else:
            txt = re.sub(r"packagingOptions\s*\{[\s\S]*?\}",
                         """packagingOptions {
        resources {
            excludes += ["META-INF/AL2.0", "META-INF/LGPL2.1", "META-INF/LICENSE*", "META-INF/NOTICE*", "META-INF/DEPENDENCIES"]
        }
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    packagingOptions {
        resources {
            excludes += ["META-INF/AL2.0", "META-INF/LGPL2.1", "META-INF/LICENSE*", "META-INF/NOTICE*", "META-INF/DEPENDENCIES"]
        }
    }""", txt, count=1)

    # зависимости: desugar + multidex
    if "dependencies" in txt:
        if "coreLibraryDesugaring" not in txt:
            txt = re.sub(r"dependencies\s*\{",
                         f"""dependencies {{
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:{DESUGAR_VER}" """,
                         txt, count=1)
        if "androidx.multidex:multidex" not in txt:
            txt = re.sub(r"dependencies\s*\{",
                         f"""dependencies {{
    implementation "androidx.multidex:multidex:{MULTIDEX_VER}" """,
                         txt, count=1)
    else:
        txt += f"""

dependencies {{
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:{DESUGAR_VER}"
    implementation "androidx.multidex:multidex:{MULTIDEX_VER}"
}}
"""

    write(f, txt)

# ---------------- Kotlin DSL ----------------
def patch_app_kts(f: pathlib.Path):
    if not f.exists():
        write(f, f"""// Generated by patch_gradle.py (KTS)
plugins {{
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}}

android {{
    compileSdk = 34

    defaultConfig {{
        applicationId = "com.example.bp_logger"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        multiDexEnabled = true
    }}

    buildTypes {{
        release {{
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }}
    }}

    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }}
    kotlinOptions {{
        jvmTarget = "17"
    }}

    lint {{
        abortOnError = false
        checkReleaseBuilds = false
    }}

    packaging {{
        resources {{
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }}
    }}
}}

dependencies {{
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:{DESUGAR_VER}")
    implementation("androidx.multidex:multidex:{MULTIDEX_VER}")
}}
""")
        return

    txt = read(f)

    # compileOptions + desugaring
    if "compileOptions" in txt:
        txt = re.sub(r"compileOptions\s*\{[\s\S]*?\}",
                     """compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }""", txt, count=1)

    # kotlinOptions jvmTarget=17
    if "kotlinOptions" in txt:
        txt = re.sub(r'kotlinOptions\s*\{[\s\S]*?\}',
                     'kotlinOptions {\n        jvmTarget = "17"\n    }', txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    kotlinOptions {
        jvmTarget = "17"
    }""", txt, count=1)

    # defaultConfig { multiDexEnabled = true }
    if re.search(r"defaultConfig\s*\{", txt):
        if not re.search(r"multiDexEnabled\s*=\s*true", txt):
            txt = re.sub(r"(defaultConfig\s*\{[^\}]*?)\}",
                         r"\1\n        multiDexEnabled = true\n    }",
                         txt, count=1)
    else:
        txt = re.sub(r"android\s*\{",
                     """android {
    defaultConfig {
        multiDexEnabled = true
    }""", txt, count=1)

    # lint { abortOnError=false; checkReleaseBuilds=false }
    if re.search(r"\blint\s*\{", txt):
        txt = re.sub(r"lint\s*\{[\s\S]*?\}",
                     """lint {
        abortOnError = false
        checkReleaseBuilds = false
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    lint {
        abortOnError = false
        checkReleaseBuilds = false
    }""", txt, count=1)

    # packaging { resources.excludes += ... }
    if re.search(r"\bpackaging\s*\{", txt):
        txt = re.sub(r"packaging\s*\{[\s\S]*?\}",
                     """packaging {
        resources {
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }
    }""", txt, count=1)
    else:
        txt = re.sub(r"android\s*\{", """android {
    packaging {
        resources {
            excludes += setOf("META-INF/AL2.0","META-INF/LGPL2.1","META-INF/LICENSE*","META-INF/NOTICE*","META-INF/DEPENDENCIES")
        }
    }""", txt, count=1)

    # зависимости
    if "coreLibraryDesugaring(" not in txt:
        txt = re.sub(r"dependencies\s*\{", f"""dependencies {{
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:{DESUGAR_VER}") """, txt, count=1)
    if "androidx.multidex:multidex" not in txt:
        txt = re.sub(r"dependencies\s*\{", f"""dependencies {{
    implementation("androidx.multidex:multidex:{MULTIDEX_VER}") """, txt, count=1)

    write(f, txt)

def main():
    if len(sys.argv) < 1:
        print("Usage: python3 tools/patch_gradle.py app_or_app_android", file=sys.stderr)
        sys.exit(1)

    target = sys.argv[1] if len(sys.argv) >= 2 else "app"
    app_dir = norm_app(target)

    app_groovy = app_dir / "android" / "app" / "build.gradle"
    app_kts    = app_dir / "android" / "app" / "build.gradle.kts"

    if app_kts.exists() and not app_groovy.exists():
        patch_app_kts(app_kts)
    elif app_groovy.exists():
        patch_app_groovy(app_groovy)
    else:
        # если шаблон не создан — создаём современный KTS
        patch_app_kts(app_kts)

    print("✅ Patch applied: Java17 + desugaring + multidex + lint + packaging (Groovy/KTS).")

if __name__ == "__main__":
    main()
